apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscriptions.yaml
  - group-cr.yaml
  - group-sync-ldapca-secret.yaml
generatorOptions:
  disableNameSuffixHash: true

