apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - metallb/ippool.yaml
  - metallb/l2adv.yaml
  - auth/ldap-secret.yaml
  - group-sync/group-sync-ldap-secret.yaml

patches:
  - path: auth/patch-oauth-binddn.yaml
    target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster

