apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - metallb/ippool.yaml
  - metallb/l2adv.yaml
  - auth/ldap-secret.yaml
  - auth/patch-oauth-binddn.yaml
  - group-sync/group-sync-ldap-secret.yaml
patchesStrategicMerge:
  - auth/patch-oauth-binddn.yaml
