apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ca-config-map
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDmTCCAoGgAwIBAgIQX+5pVgEYDbxG9Ud1OCYlkzANBgkqhkiG9w0BAQsFADBT
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRswGQYKCZImiZPyLGQBGRYLa29kZXZpcnR1
    YWwxHzAdBgNVBAMTFmxhYi1kYy5rb2RldmlydHVhbC5jb20wHhcNMjQwMjE1MTEx
    MTUwWhcNMjkwMjE1MTEyMTQ5WjBTMRMwEQYKCZImiZPyLGQBGRYDY29tMRswGQYK
    CZImiZPyLGQBGRYLa29kZXZpcnR1YWwxHzAdBgNVBAMTFmxhYi1kYy5rb2Rldmly
    dHVhbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcTwF3Ry8G
    lpybLSydzkSAifHb45FTeOLPEIOG5Thj+BUHJ4VG8P080OowY8LdjZmbyfbFuLOf
    aarTszZH75RdgFE0hV7kD/SGUzK4JmsZn7QWPhsH8L57ip/sxuInElLlSM6o/NYP
    8dCwsZjgkT741QaipJL+MbSJXev7OBYuAFVLud/NJpvSJ54YpA8G+LVAZv693JE2
    95Os7MtyWrrwLMrsGpfBctrk9ArSJySFkzvLLOlX5mGYEy1Cc/bzNSSTHkky+GX5
    8c492JC+UA2GVjhkutXcPIw50DWVS+TbJ3tAoSziJL42LxKHzsJ35yL+EjoRK9Vx
    ffHBo2X37eUdAgMBAAGjaTBnMBMGCSsGAQQBgjcUAgQGHgQAQwBBMA4GA1UdDwEB
    /wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSz9iJXXiG4Q2iikWmG
    1TKqrl982jAQBgkrBgEEAYI3FQEEAwIBADANBgkqhkiG9w0BAQsFAAOCAQEAcm3I
    JzLApJ+7YK0pim7xr26lACKIgcoR3kJ2O3i+FES9c4z3korqhgokZTnTTh1mGENy
    Gyarcvm5d7PvShaMtX1IWEkoCmW7Xa0mjB4BYMLwxceLauQEqTldBO3sku4EOtx5
    RETqb81bJ4IZpipDks6LLY/5G+K+pCqxEAC1etEEXeSeH01MB1OnmuLA2iCktci/
    AKbfkbL0V9Fic2YqzNG4WyCOBtVeh0sgr9ZWOP0spe8OAw8cKOy2/e8gr3ZWlYAH
    EJDBSZyxPOoAYQ7nIcaheTaud3WdLxbS1ASmspiG56iUTsqKB4EzhsYRg1elJ9IQ
    P01w1Zl5U673H1VR/A==
    -----END CERTIFICATE-----
